/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;
import java.awt.event.ActionListener;
import java.util.HashMap;

import javax.swing.JOptionPane;

import domen.Korisnik;
import konstante.Operacije;
import logika.Komunikacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.SystemColor;
import javax.swing.border.EmptyBorder;

/**
 *Klasa koja predstavlja GKI i sluzi za prijavu korisnika na sistem
 *sa korisnickim imenom i lozinkom. Nasledjuje {@link javax.swing.JFrame }.
 * @author Mirjana Dimitrijevic
 */
public class LoginForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentForma
     */
    public LoginForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String un=txtKorisnickoIme.getText();
        		String pass= String.valueOf(txtLozinka.getPassword());
        		
        		HashMap<String, String> mapa = new HashMap<String, String>();
        		mapa.put("b", pass);
        		mapa.put("a", un);
        		KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.LOGIN, mapa);
        		Komunikacija.getInstance().posaljiZahtev(kz);
        		ServerskiOdgovor so= Komunikacija.getInstance().primiOdgovor();
        		Korisnik korisnik= (Korisnik) so.getOdgovor();
        		if(korisnik==null) 
        			JOptionPane.showMessageDialog(null, "Pogresno korisnicko ime ili lozinka, pokusajte ponovo.", "Netacni kredencijali", JOptionPane.ERROR_MESSAGE);
        	 else {
        		KlijentForma kf= new KlijentForma();
        		kf.setKorisnik(korisnik);
        		kf.setVisible(true);
        		dispose();
        	 	
        	}
        }});
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Prijavite se");

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Lozinka:");
        
        lblNewLabel = new JLabel("Nemate nalog?");
        
        JButton btnNewButton = new JButton("Registrujte se");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		RegistracijaForma rf= new RegistracijaForma();
        		rf.setVisible(true);
        		dispose();
        	}
        });
        btnNewButton.setBorder(new EmptyBorder(0, 0, 0, 0));
        btnNewButton.setBackground(SystemColor.menu);
        btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 11));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(145)
        					.addComponent(jButton1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(43)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addComponent(jLabel2))
        					.addPreferredGap(ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(txtKorisnickoIme)
        						.addComponent(txtLozinka, GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
        			.addGap(28))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(12)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(62)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtKorisnickoIme, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtLozinka, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        			.addComponent(jButton1)
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        			.addGap(8))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtLozinka;
    private JLabel lblNewLabel;
}
