package forme;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import domen.ElementProizvoda;
import domen.JedinicaMere;
import domen.Korisnik;
import domen.Materijal;
import domen.Proizvod;
import konstante.Operacije;
import logika.Komunikacija;
import modeli.ModelTabeleElementProizvoda;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.awt.event.ActionEvent;

/**
 *
 * @author 38169
 */
public class NoviProizvodForma extends javax.swing.JFrame {
Korisnik ulogovaniKorisnik;
    /**
     * Creates new form NoviProizvodForma
     */
    public NoviProizvodForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Novi proizvod");
        popuniMaterijale();
        popuniJediniceMere();
        jTable1.setModel(new ModelTabeleElementProizvoda());

        
    }

    private void popuniJediniceMere() {
		cmbJM.removeAllItems();
		KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.PRIKAZI_SVE_JM, null);
		Komunikacija.getInstance().posaljiZahtev(kz);
		ServerskiOdgovor so= Komunikacija.getInstance().primiOdgovor();
		ArrayList<JedinicaMere> jms=(ArrayList<JedinicaMere>) so.getOdgovor();
	for (JedinicaMere jedinicaMere : jms) {
		cmbJM.addItem(jedinicaMere);
	}
    }

	private void popuniMaterijale() {
		cmbMaterijal.removeAllItems();
		KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.PRIKAZI_SVE_MATERIJALE, null);
		Komunikacija.getInstance().posaljiZahtev(kz);
		ServerskiOdgovor so= Komunikacija.getInstance().primiOdgovor();
		ArrayList<Materijal> materijals = (ArrayList<Materijal>) so.getOdgovor();
		for (Materijal materijal : materijals) {
			cmbMaterijal.addItem(materijal);
		}
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String naziv= txtNaziv.getText();
        		String opis= txtOpis.getText();
        		double kolcina= Double.valueOf(txtKolicina.getText().replace(',', '.'));
        		boolean patent= rDa.isSelected();
        		int vt= Integer.valueOf(txtVremeTrajnja.getText());
        		Calendar today= Calendar.getInstance();
        		java.util.Date datum=today.getTime();
    			ModelTabeleElementProizvoda mtep= (ModelTabeleElementProizvoda) jTable1.getModel();
        		Proizvod proizvod = new Proizvod(-1, naziv, opis, kolcina, patent, vt, datum, ulogovaniKorisnik, mtep.getLista());
        		
        		KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.SACUVAJ_PROIZVOD, proizvod);
        		Komunikacija.getInstance().posaljiZahtev(kz);
        		ServerskiOdgovor so= Komunikacija.getInstance().primiOdgovor();
       
        		if((Boolean) so.getOdgovor()) {
        			JOptionPane.showMessageDialog(null, "Proizvod je uspešno saèuvan", "Èuvanje uspešno", JOptionPane.INFORMATION_MESSAGE);

        		} else         			JOptionPane.showMessageDialog(null, "Došlo je do greške, pokušajte ponovo", "Èuvanje nije omoguæeno", JOptionPane.ERROR_MESSAGE);

        	}
        });
        txtNaziv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtVremeTrajnja = new javax.swing.JFormattedTextField();
        rDa = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtKolicina = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbMaterijal = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbJM = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtKolMat = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int row= jTable1.getSelectedRow();
        		if(row!=-1) {
        			ModelTabeleElementProizvoda mtep= (ModelTabeleElementProizvoda) jTable1.getModel();
        		    mtep.obrisiMaterijal(row);
        		}
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(txtKolMat.getText().isEmpty()) {
        			JOptionPane.showMessageDialog(null, "Sva polja moraju biti popunjena!", "Dodavanje materijala nije omoguæeno", JOptionPane.WARNING_MESSAGE);
        		return;
        		}
        	JedinicaMere jm= (JedinicaMere) cmbJM.getSelectedItem();
        	Materijal mat= (Materijal) cmbMaterijal.getSelectedItem();
        	double kolicina= Double.valueOf(txtKolMat.getText().replace(',', '.'));	
        	ElementProizvoda ep= new ElementProizvoda(null, -1, mat, jm, kolicina);
        	
        	ModelTabeleElementProizvoda mtep= (ModelTabeleElementProizvoda) jTable1.getModel();
        	mtep.dodajMaterijal(ep);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Naziv proizvoda:");

        jLabel2.setText("Opis proizvoda:");

        jLabel3.setText(" Kolièina na stanju:");

        jLabel4.setText(" Patent:");

        jLabel5.setText("Vreme trajanja (u mesecima):");

        jButton1.setText("Saèuvaj proizvod");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        txtVremeTrajnja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        buttonGroup1.add(rDa);
        rDa.setSelected(true);
        rDa.setText("da");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("ne");

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel7.setText("Materijal:");

        jLabel8.setText("Jedinica mere:");

        jLabel9.setText("Kolièina materijala za proizvod:");

        txtKolMat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Obriši izabrani materijal ");

        jButton3.setText("Dodaj materijal u sastavnicu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(14)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel6)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel7)
        							.addGap(94)
        							.addComponent(cmbMaterijal, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(jLabel9)
        								.addGap(18)
        								.addComponent(txtKolMat))
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(jLabel8)
        								.addGap(68)
        								.addComponent(cmbJM, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(txtVremeTrajnja))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(jLabel3, Alignment.TRAILING)
        									.addGroup(layout.createSequentialGroup()
        										.addGap(4)
        										.addComponent(jLabel2)))
        								.addComponent(jLabel4)
        								.addComponent(jLabel1))
        							.addGap(18)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(rDa)
        									.addGap(18)
        									.addComponent(jRadioButton2))
        								.addComponent(txtNaziv)
        								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtKolicina)))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jButton3)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jButton2)
        							.addGap(14))
        						.addComponent(jButton1))))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtNaziv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel1))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(59)
        					.addComponent(jLabel2)))
        			.addGap(12)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(txtKolicina, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(15)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(rDa)
        				.addComponent(jRadioButton2))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(txtVremeTrajnja, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addComponent(jLabel6)
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(cmbMaterijal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(cmbJM, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel9)
        				.addComponent(txtKolMat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(33)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(34, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
        					.addComponent(jButton3)
        					.addGap(18)
        					.addComponent(jButton2)
        					.addGap(26)
        					.addComponent(jButton1)
        					.addGap(69))))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
   
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoviProizvodForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoviProizvodForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoviProizvodForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoviProizvodForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoviProizvodForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbMaterijal;
    private javax.swing.JComboBox cmbJM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rDa;
    private javax.swing.JFormattedTextField txtKolMat;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JFormattedTextField txtVremeTrajnja;
    // End of variables declaration                   
	public void setKorisnik(Korisnik korisnik) {
		ulogovaniKorisnik=korisnik;
	}
}
